// Copies Keepsake's three typefaces out of the @fontsource packages into
// keepsake/public/fonts and writes keepsake/src/fonts.css. Run by the
// "Vendor fonts" workflow so the site never asks a font service for anything.
//   node vendor-fonts.mjs <dir where packages were installed> <keepsake dir>
import {copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

const [work, out] = process.argv.slice(2);
// family, package, weight range, and per style the axis files to prefer (first that exists wins)
const fonts = [
  ['Inter', '@fontsource-variable/inter', '100 900', {normal: ['wght']}],
  ['Fraunces', '@fontsource-variable/fraunces', '100 900', {normal: ['full', 'opsz', 'wght'], italic: ['full', 'opsz', 'wght']}],
  ['Caveat', '@fontsource-variable/caveat', '400 700', {normal: ['wght']}],
];
const ranges = {
  latin: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  'latin-ext': 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
};
const dest = join(out, 'public', 'fonts');
mkdirSync(join(dest, 'LICENSES'), {recursive: true});
let css = '/* Generated by .github/scripts/vendor-fonts.mjs (workflow "Vendor fonts"). Self-hosted so no visitor address is sent to a font service. SIL OFL 1.1; see public/fonts/LICENSES. */\n';
const licences = [];
for (const [family, pkg, weights, styles] of fonts) {
  const dir = join(work, 'node_modules', pkg, 'files');
  const files = readdirSync(dir);
  console.log(`${family}: ${files.filter(f => f.includes('-latin-')).join(', ')}`);
  for (const [style, axes] of Object.entries(styles)) {
    for (const subset of Object.keys(ranges)) {
      const file = axes.map(axis => files.find(f => f.endsWith(`-${subset}-${axis}-${style}.woff2`))).find(Boolean);
      if (!file) { console.warn(`skip ${family} ${style} ${subset}: no matching file`); continue; }
      const name = `${family.toLowerCase()}-${subset}-${style}.woff2`;
      copyFileSync(join(dir, file), join(dest, name));
      css += `@font-face{font-family:"${family}";font-style:${style};font-weight:${weights};font-display:swap;src:url("/fonts/${name}") format("woff2");unicode-range:${ranges[subset]};}\n`;
      console.log(`  ${style} ${subset}: ${file} -> ${name}`);
    }
  }
  const licence = join(work, 'node_modules', pkg, 'LICENSE');
  if (existsSync(licence)) licences.push(`=== ${family} (${pkg}) ===\n${readFileSync(licence, 'utf8')}`);
}
writeFileSync(join(out, 'src', 'fonts.css'), css);
writeFileSync(join(dest, 'LICENSES', 'README.txt'), 'Inter, Fraunces and Caveat are licensed under the SIL Open Font License 1.1 (https://openfontlicense.org).\n\n' + licences.join('\n\n'));
