import type {AppState} from '../types/app';
function rememberPoster(s:AppState,posterItem?:string){
 const d=s.roomDecor??{owned:[]},room=s.environment?.roomTheme??'woodland',layout=d.layouts?.[room];
 return {...d,posterItem,layouts:{...d.layouts,[room]:{...layout,posterItem,crtColor:layout?.crtColor??s.environment?.crtColor}}};
}
export const ROOM_GOODS=[{id:'holo-cat',title:'Hologram cat',price:0,kind:'Hologram',icon:'🐈',description:'A luminous cat for Neon City.'},{id:'holo-car',title:'Hologram car',price:0,kind:'Hologram',icon:'🚙',description:'A miniature light-built coupe for Neon City.'},{id:'holo-flower',title:'Hologram flower',price:0,kind:'Hologram',icon:'🌸',description:'A glowing blossom for Neon City.'},{id:'fern',title:'Little woodland fern',price:3,kind:'Plant',icon:'🌿',description:'A soft green fern in a clay pot.'},{id:'fox',title:'Sleepy clay fox',price:4,kind:'Figurine',icon:'🦊',description:'A curled-up fox with a cream-tipped tail.'},{id:'bird',title:'Brass songbird',price:4,kind:'Figurine',icon:'🐦',description:'A small warm brass bird on an oak base.'},{id:'vase',title:'Wildflower bud vase',price:3,kind:'Knick-knack',icon:'🌼',description:'One yellow flower in a moss-glazed vase.'}] as const;
export function buyRoomGood(s:AppState,id:string):AppState{const item=ROOM_GOODS.find(i=>i.id===id);const d=s.roomDecor??{owned:[]};if(!item||d.owned.includes(id)||s.stamps<item.price)return s;return {...s,stamps:s.stamps-item.price,roomDecor:{...d,owned:[...d.owned,id],sillItem:id}};}
export function placeRoomGood(s:AppState,id?:string):AppState{const d=s.roomDecor??{owned:[]};if(id&&(!d.owned.includes(id)||!ROOM_GOODS.some(i=>i.id===id)))return s;return {...s,roomDecor:{...d,sillItem:id}};}
export const EXTRA_GOODS=[{id:'sparkle-markers',title:'Sparkly marker pair',price:4,kind:'Markers',icon:'✨',description:'Gold and rose ink with tiny paper glints.'},{id:'fern-stamp',title:'Woodland fern stamp',price:2,kind:'Stamp',icon:'🌿',description:'A reusable fern imprint in the scrapbook sticker tray.'},{id:'poster-botanical',title:'Botanical field poster',price:3,kind:'Poster',icon:'🌱',description:'A cream paper study of woodland leaves.'},{id:'poster-night',title:'Moonlit mountain poster',price:3,kind:'Poster',icon:'🌙',description:'An ink-blue sky above quiet mountains.'}] as const;
export const NEON_EXTRAS=[{id:'neon-cherries',title:'Cherry neon sign',price:0,kind:'Sign',icon:'🍒',description:'Two glowing cherries above the light switch.'},{id:'neon-heart',title:'Red heart neon sign',price:0,kind:'Sign',icon:'♥',description:'A glowing red heart for the shared sign spot.'},{id:'poster-snake',title:'Snake maze poster',price:0,kind:'Poster',icon:'▦',description:'An endlessly played Snake game in a neon frame.'}] as const;
export const SHOP_GOODS=[...ROOM_GOODS,...EXTRA_GOODS,...NEON_EXTRAS];
export const POSTER_GOODS=[...EXTRA_GOODS,...NEON_EXTRAS].filter(i=>i.kind==='Poster');
export function getNeonSign(d:AppState['roomDecor']){const id=d?.neonSign!==undefined?d.neonSign:d?.neonCherry?'neon-cherries':null;return id&&d?.owned.includes(id)?id:null;}
export function placeNeonSign(s:AppState,id:'neon-cherries'|'neon-heart'|null):AppState{const d=s.roomDecor??{owned:[]};if(id&&!d.owned.includes(id))return s;return {...s,roomDecor:{...d,neonSign:id,neonCherry:id==='neon-cherries'}};}
export function placeNeonCherry(s:AppState,placed:boolean):AppState{return placeNeonSign(s,placed?'neon-cherries':null);}
export function buyNeonExtra(s:AppState,id:string):AppState{const item=NEON_EXTRAS.find(i=>i.id===id);const d=s.roomDecor??{owned:[]};if(s.environment.roomTheme!=='cyberpunk'||!item||d.owned.includes(id))return s;const owned=[...d.owned,id];return item.kind==='Sign'?placeNeonSign({...s,roomDecor:{...d,owned}},item.id):{...s,roomDecor:{...rememberPoster(s,id),owned}};}
export const SPARKLE_INKS={'sparkly gold':'#bf9955','sparkly rose':'#cc75bc'};
export function buyExtra(s:AppState,id:string):AppState{const item=EXTRA_GOODS.find(i=>i.id===id);const d=s.roomDecor??{owned:[]};if(!item||d.owned.includes(id)||s.stamps<item.price)return s;const owned=[...d.owned,id];return {...s,stamps:s.stamps-item.price,roomDecor:item.kind==='Poster'?{...rememberPoster(s,id),owned}:{...d,owned}};}
export function placePoster(s:AppState,id?:string):AppState{const d=s.roomDecor??{owned:[]};if(id&&(!d.owned.includes(id)||!POSTER_GOODS.some(i=>i.id===id)))return s;return {...s,roomDecor:rememberPoster(s,id)};}
