import type {AppState} from '../types/app';
export const ROOM_GOODS=[{id:'fern',title:'Little woodland fern',price:3,kind:'Plant',icon:'🌿',description:'A soft green fern in a clay pot.'},{id:'fox',title:'Sleepy clay fox',price:4,kind:'Figurine',icon:'🦊',description:'A curled-up fox with a cream-tipped tail.'},{id:'bird',title:'Brass songbird',price:4,kind:'Figurine',icon:'🐦',description:'A small warm brass bird on an oak base.'},{id:'vase',title:'Wildflower bud vase',price:3,kind:'Knick-knack',icon:'🌼',description:'One yellow flower in a moss-glazed vase.'}] as const;
export function buyRoomGood(s:AppState,id:string):AppState{const item=ROOM_GOODS.find(i=>i.id===id);const d=s.roomDecor??{owned:[]};if(!item||d.owned.includes(id)||s.stamps<item.price)return s;return {...s,stamps:s.stamps-item.price,roomDecor:{...d,owned:[...d.owned,id],sillItem:id}};}
export function placeRoomGood(s:AppState,id?:string):AppState{const d=s.roomDecor??{owned:[]};if(id&&(!d.owned.includes(id)||!ROOM_GOODS.some(i=>i.id===id)))return s;return {...s,roomDecor:{...d,sillItem:id}};}
export const EXTRA_GOODS=[{id:'sparkle-markers',title:'Sparkly marker pair',price:4,kind:'Markers',icon:'✨',description:'Gold and rose ink with tiny paper glints.'},{id:'fern-stamp',title:'Woodland fern stamp',price:2,kind:'Stamp',icon:'🌿',description:'A reusable fern imprint in the scrapbook sticker tray.'},{id:'poster-botanical',title:'Botanical field poster',price:3,kind:'Poster',icon:'🌱',description:'A cream paper study of woodland leaves.'},{id:'poster-night',title:'Moonlit mountain poster',price:3,kind:'Poster',icon:'🌙',description:'An ink-blue sky above quiet mountains.'}] as const;
export const SHOP_GOODS=[...ROOM_GOODS,...EXTRA_GOODS];
export const SPARKLE_INKS={'sparkly gold':'#bf9955','sparkly rose':'#cc75bc'};
export function buyExtra(s:AppState,id:string):AppState{const item=EXTRA_GOODS.find(i=>i.id===id);const d=s.roomDecor??{owned:[]};if(!item||d.owned.includes(id)||s.stamps<item.price)return s;return {...s,stamps:s.stamps-item.price,roomDecor:{...d,owned:[...d.owned,id],...(item.kind==='Poster'?{posterItem:id}:{})}};}
export function placePoster(s:AppState,id?:string):AppState{const d=s.roomDecor??{owned:[]};if(id&&(!d.owned.includes(id)||!EXTRA_GOODS.some(i=>i.id===id&&i.kind==='Poster')))return s;return {...s,roomDecor:{...d,posterItem:id}};}
