import assert from 'node:assert/strict';
import {claimDailyStamps,localDayKey,DAILY_STAMPS,STAMP_CAP,STARTING_STAMPS} from '../src/lib/stamps.ts';
import {readFileSync} from 'node:fs';
import {parseRoomBackup,serializeRoom} from '../src/lib/roomBackup.ts';
assert.equal(STARTING_STAMPS,30);assert.match(readFileSync(new URL('../src/data/seed.ts',import.meta.url),'utf8'),/stamps: STARTING_STAMPS/,'new rooms start with the starting amount');
const d1=new Date(2026,9,10,9),d1b=new Date(2026,9,10,23,59),d2=new Date(2026,9,11,8),d9=new Date(2026,9,19);
let s={version:1,profile:{displayName:'Test'},books:[{id:'book',title:'A memory',subtitle:'',coverStyle:'forest',visibility:'private',createdAt:1,updatedAt:1,pages:[{id:'p1',elements:[]}]}],activeBookId:'book',archive:[],archiveTabs:[],pins:[],guestbook:[],notes:[],pinNotes:[],achievements:[],achievementsSeen:[],ownedStickerPacks:['everyday'],stamps:12,achievementsAt:{},receipts:{},progress:{visitedAtNight:false,previewedAsVisitor:false,completedTour:false},environment:{timeMode:'day',season:'autumn',weather:'clear',musicProvider:'ambient',lampOn:true,ceilingOn:true,shelfLit:true,musicOn:false,pinsLocked:false,volume:.5,ambienceVolume:.4,roomQuality:'high'},roomDecor:{owned:['fox','bird','poster-night'],sillItem:'fox',posterItem:'poster-night'}};s.stamps=STARTING_STAMPS;
const a=claimDailyStamps(s,d1);assert.equal(a.stamps,30+DAILY_STAMPS);assert.equal(a.stampsClaimedOn,'2026-10-10');
assert.equal(claimDailyStamps(a,d1b),a,'once per day, same object back');
assert.equal(claimDailyStamps(a,d2).stamps,30+2*DAILY_STAMPS);
const gap=claimDailyStamps(a,d9);assert.equal(gap.stamps,30+2*DAILY_STAMPS,'a long absence grants the same as one day: nothing stacks, nothing is lost');
const keys=Object.keys(gap);assert.ok(!keys.some(k=>/streak|combo|multiplier/i.test(k)),'no streak state exists');
const near={...s,stamps:STAMP_CAP-1};assert.equal(claimDailyStamps(near,d1).stamps,STAMP_CAP,'balance cap');
const over={...s,stamps:150};assert.equal(claimDailyStamps(over,d1).stamps,150,'never takes stamps away');
assert.equal(claimDailyStamps(over,d1).stampsClaimedOn,'2026-10-10');
assert.equal(localDayKey(new Date(2027,0,5)),'2027-01-05');
assert.equal(parseRoomBackup(serializeRoom(a)).stampsClaimedOn,'2026-10-10','survives backup');
assert.throws(()=>parseRoomBackup(serializeRoom({...a,stampsClaimedOn:'yesterday'})));
console.log('Daily stamps: 30 to start, a small fixed daily grant, capped, no streaks, nothing lost.');
