import {MELLOW_SKIES} from '../lib/roomMusic';
import {startWithGesture} from '../lib/musicAutoplay';
import {useEffect,useRef,useState} from 'react';
import {useApp} from '../store/appStore';
import {useCrtPlayerSlot} from '../store/spotifyUi';
import {VolumeSlider} from './VolumeSlider';
interface Widget {play:()=>void;bind:(event:string,fn:()=>void)=>void;unbind:(event:string)=>void;toggle:()=>void;next:()=>void;prev:()=>void;setVolume:(v:number)=>void;getCurrentSound:(fn:(s:{title:string;user?:{username:string}})=>void)=>void;isPaused:(fn:(v:boolean)=>void)=>void}
type SCAPI={Widget:((el:HTMLIFrameElement)=>Widget)&{Events:Record<string,string>}};
let loading:Promise<SCAPI>|undefined;
function loadWidget(){return loading??=new Promise<SCAPI>((resolve,reject)=>{const script=document.createElement('script');script.src='https://w.soundcloud.com/player/api.js';script.onload=()=>resolve((window as unknown as {SC:SCAPI}).SC);script.onerror=()=>{loading=undefined;script.remove();reject(new Error('Player unavailable'));};document.head.append(script);});}
export function SoundCloudDock(){const {environment}=useApp();return (environment.musicProvider==='lofi'||environment.musicProvider==='soundcloud'&&environment.soundCloudUrl)?<SoundCloudPlayer key={environment.musicProvider+environment.soundCloudUrl}/>:null;}
function SoundCloudPlayer(){
 const {environment,setEnvironment}=useApp();const source=environment.musicProvider==='lofi'?MELLOW_SKIES:environment.soundCloudUrl!;const {setNowPlaying,nowPlaying}=useCrtPlayerSlot();const frame=useRef<HTMLIFrameElement>(null);const widget=useRef<Widget|null>(null);const [expanded,setExpanded]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState(false);const [reload,setReload]=useState(0);const volume=useRef(environment.volume);
 useEffect(()=>{volume.current=environment.volume;widget.current?.setVolume(environment.volume*100);},[environment.volume]);
 useEffect(()=>{if(!environment.musicOn)return;let alive=true;let unbind=()=>{};let cancelStart=()=>{};setReady(false);setError(false);loadWidget().then(api=>{if(!alive||!frame.current)return;const w=api.Widget(frame.current);widget.current=w;const sync=()=>{if(!alive||!frame.current?.isConnected)return;w.getCurrentSound(sound=>{if(!alive||!frame.current?.isConnected)return;w.isPaused(paused=>{if(alive)setNowPlaying({title:sound.title,artist:sound.user?.username??'SoundCloud',paused});});});};const events=api.Widget.Events;w.bind(events.READY,()=>{if(alive){setReady(true);w.setVolume(volume.current*100);cancelStart=startWithGesture(()=>w.play());sync();}});w.bind(events.PLAY,()=>{cancelStart();sync();});w.bind(events.PAUSE,sync);w.bind(events.ERROR,()=>{if(alive)setError(true);});unbind=()=>[events.READY,events.PLAY,events.PAUSE,events.ERROR].forEach(e=>{try{w.unbind(e);}catch{/* The iframe can already be detached during React cleanup. */}});}).catch(()=>{if(alive)setError(true);});return()=>{alive=false;cancelStart();unbind();widget.current=null;setNowPlaying(null);};},[environment.musicOn,reload,setNowPlaying]);
 return <section data-music-controls className="ks-spotify-dock is-expanded" aria-label="SoundCloud music player"><div className="ks-music-dock-bar"><button onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>♫ SoundCloud · {expanded?'Hide':'Show'}</button>{ready&&environment.musicOn&&<><button aria-label="Previous SoundCloud track" onClick={()=>widget.current?.prev()}>‹</button><button title="If music did not start, press Play to allow sound" aria-label="Play or pause SoundCloud" onClick={()=>widget.current?.toggle()}>{nowPlaying?.paused?'Play':'Pause'}</button><button aria-label="Next SoundCloud track" onClick={()=>widget.current?.next()}>›</button></>}<button onClick={()=>setEnvironment({musicOn:!environment.musicOn})}>{environment.musicOn?'Stop':'Load player'}</button></div><div hidden={!expanded} className="p-3"><p className="text-sm">{nowPlaying?.title??'Your SoundCloud selection'} · {nowPlaying?.artist??'SoundCloud'}</p>{environment.musicOn&&<iframe key={reload} ref={frame} title="Your SoundCloud player" width="100%" height="220" allow="autoplay" src={`https://w.soundcloud.com/player/?url=${encodeURIComponent(source)}&auto_play=true${source===MELLOW_SKIES?"&start_track=3":""}&show_artwork=false&show_comments=false&show_user=true&show_reposts=false&color=%23758a64`} style={{border:0}}/>}<VolumeSlider id="lofi-volume" label="Music volume" value={environment.volume} onChange={volume=>setEnvironment({volume})}/>{source==='https://soundcloud.com/purrplecat/sets/mellow-skies'&&<small>Mellow Skies by <a href="https://purrplecat.bandcamp.com/album/mellow-skies" target="_blank" rel="noreferrer">Purrple Cat</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> · unmodified stream.</small>}{error&&<p role="status">The player could not load. Check your connection, or use Ambient music.</p>}<button className="ks-chip" onClick={()=>setReload(v=>v+1)}>Reload player</button></div></section>;
}
